[workspace]
members = [".", "kv", "kv-derive"]

[package]
name = "pkgsrc"
description = "Rust interface to pkgsrc packages and infrastructure"
version = "0.14.0"
authors = ["Jonathan Perkin <jonathan@perkin.org.uk>"]
readme = "README.md"
keywords = ["pkgsrc"]
license = "ISC"
repository = "https://github.com/jperkin/pkgsrc-rs"
homepage = "https://github.com/jperkin/pkgsrc-rs"
documentation = "https://docs.rs/pkgsrc"
rust-version = "1.88"
edition = "2024"

[dependencies]
ar = "0.9.0"
blake2 = "0.11.0-rc.6"
digest = "0.11.3"
flate2 = { version = "1.1.9", features = ["zlib-rs"], default-features = false }
glob = "0.3.4"
hashbrown = "0.17"
indexmap = { version = "2.14.0", features = ["serde"] }
md-5 = "0.11.0"
pkgsrc-kv = { path = "kv", version = "0.3.0" }
ripemd = "0.2.0"
serde = { version = "1.0.229", features = ["derive"], optional = true }
serde_with = { version = "3.21.0", optional = true }
sha1 = "0.11.0"
sha2 = "0.11.0"
smallvec = "1.15"
tar = "0.4.46"
thiserror = "2.0.19"
zstd = "0.13"

[dev-dependencies]
anyhow = "1.0"
db185 = "0.3.0"
indoc = "2"
rayon = "1.12"
regex = "1.13.1"
serde_json = "1.0"
structopt = "0.3.26"

[features]
default = []
serde = ["dep:serde", "dep:serde_with", "pkgsrc-kv/serde", "smallvec/serde"]

[profile.profiling]
inherits = "release"
debug = 2
strip = "none"
